application: sugoi-ideas
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: sugoi-ideas.app

libraries:
- name: webapp2
  version: "2.5.1"
  
- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.app
  login: admin
  
libraries:
- name: django
  version: "1.4"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?support/.*    # skip mecab binaries
- ^(.*/)?tool/.*    # skip tool apps
- ^(.*/)?testdata/.*    # skip test data
- ^(.*/)?test_.*\.py$    # skip tests
- ^(.*/)?jdict\.bin$    # skip JDIC binary
- ^(.*/)?dict\.text$    # skip JDIC CSV
